import { PrismaClient } from '@prisma/client'
const db = new PrismaClient()
async function main() {
  const users = await db.user.findMany({ where: { active: true }, select: { id: true, name: true, roles: true }, orderBy: { id: 'asc' } })
  console.log('=== ACTIVE USERS ===')
  for (const u of users) console.log(u.id, u.name, '|', u.roles)
  const suppliers = await db.supplier.findMany({ select: { id: true, name: true }, orderBy: { id: 'asc' } })
  console.log('=== SUPPLIERS ===')
  for (const s of suppliers) console.log(s.id, s.name)
  const notifs = await db.notification.findMany({ where: { title: { startsWith: 'یادآوری فهرست قیمت — ' } }, select: { id: true, userId: true, title: true, type: true, createdAt: true }, orderBy: { id: 'asc' } })
  console.log('=== NUDGE NOTIFICATIONS ===', notifs.length)
  for (const n of notifs) console.log(n.id, 'user', n.userId, n.type, n.title, n.createdAt.toISOString())
  const audits = await db.auditLog.findMany({ where: { action: 'PRICE_NUDGE_SENT' }, select: { id: true, detail: true, createdAt: true }, orderBy: { id: 'asc' } })
  console.log('=== PRICE_NUDGE_SENT audits ===')
  for (const a of audits) console.log(a.id, a.detail, a.createdAt.toISOString())
  const orders = await db.order.findMany({ where: { status: 'APPROVED' }, select: { id: true, code: true, status: true, _count: { select: { items: true } } }, orderBy: { id: 'asc' } })
  console.log('=== APPROVED ORDERS ===')
  for (const o of orders) console.log(o.id, o.code, 'items:', o._count.items)
  const tasks = await db.task.findMany({ where: { status: { in: ['OPEN', 'IN_PROGRESS'] } }, select: { id: true, title: true, status: true, priority: true, assignedToId: true, createdById: true }, orderBy: { id: 'asc' } })
  console.log('=== OPEN/IN_PROGRESS TASKS ===', tasks.length)
  for (const t of tasks) console.log(t.id, t.title, t.status, t.priority, 'assigned:', t.assignedToId, 'by:', t.createdById)
  const escAudits = await db.auditLog.findMany({ where: { action: 'NUDGE_ESCALATED' }, select: { id: true } })
  console.log('=== NUDGE_ESCALATED audits existing ===', escAudits.length)
}
main().finally(() => db.$disconnect())
